/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f1f3ff",
        "on-error": "#ffffff",
        "background": "#f9f9ff",
        "surface-container": "#e9edff",
        "on-primary-fixed": "#25005a",
        "tertiary-container": "#a15100",
        "outline-variant": "#ccc3d8",
        "on-tertiary-container": "#ffe0cd",
        "tertiary-fixed": "#ffdcc6",
        "secondary-fixed-dim": "#c7c5d1",
        "on-surface-variant": "#4a4455",
        "inverse-on-surface": "#edf0ff",
        "inverse-primary": "#d2bbff",
        "on-primary-container": "#ede0ff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-surface": "#293040",
        "on-secondary-container": "#64636d",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed": "#eaddff",
        "primary": "#630ed4",
        "surface-container-high": "#e1e8fd",
        "on-secondary-fixed": "#1a1b23",
        "on-primary-fixed-variant": "#5a00c6",
        "surface-container-highest": "#dce2f7",
        "on-secondary-fixed-variant": "#46464f",
        "primary-container": "#7c3aed",
        "on-tertiary-fixed": "#301400",
        "surface-variant": "#dce2f7",
        "surface-bright": "#f9f9ff",
        "secondary-container": "#e3e1ed",
        "outline": "#7b7487",
        "surface-container-lowest": "#ffffff",
        "on-background": "#141b2b",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d3daef",
        "surface": "#f9f9ff",
        "on-error-container": "#93000a",
        "secondary": "#5d5d67",
        "on-tertiary-fixed-variant": "#713700",
        "on-surface": "#141b2b",
        "tertiary": "#7d3d00",
        "tertiary-fixed-dim": "#ffb784",
        "surface-tint": "#732ee4",
        "primary-fixed-dim": "#d2bbff",
        "secondary-fixed": "#e3e1ed",
        "bca-blue": "#005596",
        "bibit-green": "#11C15E",
        "dark-bg": "#0e0e0e",
        "dark-surface": "#131313",
        "dark-card": "#1c1b1b",
        "dark-primary": "#7c3aed"
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-16px)' },
        }
      },
      animation: {
        float: 'float 6s ease-in-out infinite',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "48px",
        "sm": "16px",
        "base": "4px",
        "md": "24px",
        "margin-desktop": "auto",
        "xs": "8px",
        "margin-mobile": "16px",
        "gutter": "20px",
        "xl": "64px",
        "max-width": "1200px"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}